Greeting: "Howdy"
Name: "DSP-Chan"
Ray: "a drop of golden sun"
ArmLength: 3.14159
HighPrecision: true
ArmNumber: 3
Statistics: true
SuccessfulDrives: 3
Uptime: 5
ErrorFrames: 1
MainBus: "can0"
BackupBus: "can1"